# POC - Ensembling LSTM and Random Forest to Predict In-hospital Mortility

In the POC stage, we have explored the **feasibility of using LSTM to handle time series data of some high temporal data** and ensembled with random forest classifier trained on other features to predict in-hospital mortality in Phase 1. This notebook presents some of the findings based on 6-hour ICU data.

In [6]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import *
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

## LSTM for Time-Series Data

First, we define the following types of features. We will train the LSTM model for each feature in timeseries_features separately in Part 1. Then we will combine the predict probability resulted from the LSTM models with other features in catergorial_feature and aggregated_features, and train a random forest classifier to predict the in-hospital mortality in Part 2.

In [7]:
# Define feature lists
timeseries_features = ['heartrate', 'sysbp', 'diabp', 'meanbp', 'resprate', 'spo2']
categorical_features = ['ethnicity', 'gender', 'admission_type']
numerical_features = [
    'age', 'icustay_num',
    'tempc_mean', 'glucose_mean', 
    'tempc_min',  'glucose_min',
    'tempc_max',  'glucose_max', 
    'gcs_mean', 'gcsmotor_mean', 'gcsverbal_mean', 'gcseyes_mean', 'endotrachflag_mean',
    'gcs_min', 'gcsmotor_min', 'gcsverbal_min', 'gcseyes_min', 'endotrachflag_min', 
    'gcs_max', 'gcsmotor_max', 'gcsverbal_max', 'gcseyes_max', 'endotrachflag_max', 
    'baseexcess_mean', 'carboxyhemoglobin_mean', 'methemoglobin_mean', 
    'po2_mean', 'pco2_mean', 'ph_mean', 'pao2fio2ratio_mean', 'totalco2_mean', 
    'aniongap_mean', 'albumin_mean', 'bands_mean', 'bicarbonate_mean', 
    'bilirubin_mean', 'calcium_mean', 'creatinine_mean', 'chloride_mean', 
    'hematocrit_mean', 'hemoglobin_mean', 'lactate_mean', 'platelet_mean', 
    'potassium_mean', 'ptt_mean', 'inr_mean', 'sodium_mean', 'bun_mean', 'wbc_mean',
    'baseexcess_min', 'carboxyhemoglobin_min', 'methemoglobin_min',
    'po2_min', 'pco2_min', 'ph_min', 'pao2fio2ratio_min', 'totalco2_min',
    'aniongap_min', 'albumin_min', 'bands_min', 'bicarbonate_min',
    'bilirubin_min', 'calcium_min', 'creatinine_min', 'chloride_min',
    'hematocrit_min', 'hemoglobin_min', 'lactate_min', 'platelet_min',
    'potassium_min', 'ptt_min', 'inr_min', 'sodium_min', 'bun_min', 'wbc_min', 
    'baseexcess_max', 'carboxyhemoglobin_max', 'methemoglobin_max', 
    'po2_max', 'pco2_max', 'ph_max', 'pao2fio2ratio_max', 'totalco2_max',          
    'aniongap_max', 'albumin_max', 'bands_max', 'bicarbonate_max', 
    'bilirubin_max', 'calcium_max', 'creatinine_max', 'chloride_max', 
    'hematocrit_max', 'hemoglobin_max', 'lactate_max', 'platelet_max', 
    'potassium_max', 'ptt_max', 'inr_max', 'sodium_max', 'bun_max', 'wbc_max', 
    'urineoutput'
]

In [8]:
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine

load_dotenv()

# PostgreSQL connection
user = os.getenv('POSTGRESQL_USER')
password = os.getenv('POSTGRESQL_PASSWORD')
conn = create_engine(f'postgresql://{user}:{password}@localhost:5432/mimic')

For the MIMIC-III demo data used here, total 123 unique `icustay_id`s are obtained from above. As two of them has data only from 0 ~ 2 hr, there are only 121 `icustay_id`s from 3 to 6 hr.

In [9]:
# Load time-series data; different from mp_data_6hr
query = '''
    select icustay_id, hr, heartrate, sysbp, diabp, meanbp, resprate, spo2, hospital_expire_flag
    from mp_data inner join mp_cohort
        using (icustay_id)
    where hr >= 0 and hr <= 6
    order by icustay_id, hr
'''
df = pd.read_sql(query, conn)
df.head(15)

,icustay_id,hr,heartrate,sysbp,diabp,meanbp,resprate,spo2,hospital_expire_flag
0,201006,0,107.0,112.000000,64.0,80.000000,35.0,99.0,1
1,201006,1,100.0,120.000000,66.0,84.000000,32.0,93.0,1
2,201006,2,104.5,131.500000,67.5,88.833351,33.5,94.0,1
3,201006,3,104.5,134.500000,70.0,91.500000,32.5,99.5,1
4,201006,4,103.0,146.000000,71.0,96.000000,36.0,99.0,1
5,201006,5,90.0,112.000000,61.0,78.000000,32.0,99.0,1
6,201006,6,103.0,139.000000,77.0,97.666702,35.0,97.0,1
7,201204,0,77.0,146.250000,46.5,65.666667,18.5,97.5,0
8,201204,1,72.0,131.000000,50.0,68.000000,21.0,100.0,0
9,201204,2,71.5,171.000000,55.0,79.000000,18.5,99.0,0
10,201204,3,71.0,141.000000,67.0,83.000000,27.0,96.0,0
11,201204,4,60.0,93.000000,40.0,52.000000,21.0,98.0,0
12,201204,5,57.0,93.000000,34.0,49.000000,26.0,99.0,0
13,201204,6,70.0,143.000000,61.0,81.000000,14.0,100.0,0
14,203766,0,49.4,81.666667,44.5,56.888884,15.0,94.2,1

### 1) Data Preprocessing & Preparation

In [10]:
# Impute missing values of numerical time-series features with median
for col in timeseries_features:
    df.fillna({col: df[col].median()}, inplace=True)

# Split train, validation and test sets by icustay_id; 60:20:20 ratio
# As there are duplicate icustay_ids in df, split on unique icustay_ids, not df 
id_train, id_test = train_test_split(df['icustay_id'].unique(), test_size=0.2, random_state=0)
id_train, id_val = train_test_split(id_train, test_size=0.25, random_state=0)
id_train.sort()     # Sorted in place
id_val.sort()
id_test.sort()
print('Train / Validation / Test split:', id_train.shape, id_val.shape, id_test.shape)

# In-house mortality label for each icustay_id
df_label = df[['icustay_id', 'hospital_expire_flag']].drop_duplicates()

Train / Validation / Test split: (73,) (25,) (25,)

Next, we will **prepare the time-series data** to fit the LSTM model.

In [ ]:
# Pivot hr column for time-series features
df_timeseries = {}
for col in timeseries_features:
    df_tmp = df.pivot(index='icustay_id', columns='hr', values=col)
    df_tmp = df_label.merge(df_tmp, how='inner', left_on='icustay_id', right_index=True)
    df_tmp = df_tmp.fillna(0)
    df_timeseries[col] = df_tmp
    print(f'The Shape of pivol table for [{col}]:', df_timeseries[col].shape)

# Check one of the pivot tables
df_timeseries['heartrate'].tail()

The Shape of pivol table for [heartrate]: (123, 9)
The Shape of pivol table for [sysbp]: (123, 9)
The Shape of pivol table for [diabp]: (123, 9)
The Shape of pivol table for [meanbp]: (123, 9)
The Shape of pivol table for [resprate]: (123, 9)
The Shape of pivol table for [spo2]: (123, 9)

,icustay_id,hospital_expire_flag,0,1,2,3,4,5,6
822,295043,1,106.5,110.0,104.500000,109.0,86.833333,104.0,91.0
829,295741,0,90.5,80.5,81.000000,86.0,82.000000,76.0,78.0
836,296804,0,71.5,75.6,70.500000,70.0,68.666667,74.0,78.0
843,297782,1,96.0,97.0,86.833333,0.0,0.000000,0.0,0.0
846,298685,1,69.8,74.0,87.000000,86.0,89.000000,90.0,99.0

### 2) Define Class & Functions for LSTM

The time-series dataset is ready. Now, we define 2 methods to train LSTM and make prediction.

In [96]:
# Define LSTM classifier class
class LSTMClassifier(nn.Module):
    def __init__(self, feature_dim, hidden_dim=5):   # Hidden_dim should be adjusted for original MIMIC-III

        super().__init__()
        self.lstm = nn.LSTM(input_size=feature_dim, hidden_size=hidden_dim, batch_first=True)
        self.fc = nn.Linear(in_features=hidden_dim, out_features=1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, X):
        # X shape: (batch, timesteps, feature_dim
        # output shape: (batch, timesteps, hidden_dim), h_n/c_n shape: (num_layers, batch, hidden_dim)
        output, (h_n, c_n) = self.lstm(X)
        out = self.fc(h_n[-1])     # Hidden state in the last layer
        return self.sigmoid(out).squeeze(-1)   # Shape: (batch, 1) -> (batch,)

In [ ]:
def train_lstm(df_train, df_val):

    # Separate X and y
    X_train = df_train.drop(columns=['icustay_id', 'hospital_expire_flag'])
    y_train = df_train['hospital_expire_flag']
    X_val = df_val.drop(columns=['icustay_id', 'hospital_expire_flag'])
    y_val = df_val['hospital_expire_flag']

    # Reshape X into [samples (depth), timesteps (rows), time features (columns)]
    X_train = np.reshape(X_train, (X_train.shape[0], 1, X_train.shape[1]))
    X_val = np.reshape(X_val, (X_val.shape[0], 1, X_val.shape[1]))

    feature_dim = X_train.shape[2]
    timesteps = X_train.shape[1]

    # Transform to tensor
    X_train_tensor = torch.tensor(X_train, dtype=torch.float32, device=device)
    y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32, device=device)
    X_val_tensor = torch.tensor(X_val, dtype=torch.float32, device=device)
    y_val_tensor = torch.tensor(y_val.values, dtype=torch.float32, device=device)

    # Combine X, y and set data loader
    trainset_tensor = TensorDataset(X_train_tensor, y_train_tensor)
    trainset_loader = DataLoader(trainset_tensor, batch_size=3, shuffle=True)  # Batch size should be adjusted for original MIMIC-III

    # Build the LSTM model
    model = LSTMClassifier(feature_dim=feature_dim, hidden_dim=5).to(device)  # hidden_dim should be adjusted for original MIMIC-III
    criterion = nn.BCELoss()
    optimizer = torch.optim.Adam(model.parameters())

    # Train the model
    model.train()

    for epoch in range(10):
        for X, y in trainset_loader:   # One batch of X, y
            optimizer.zero_grad()      # w.grad = 0 (△w = 0)
            y_pred = model(X)
            loss = criterion(y_pred, y) 
            loss.backward()            # w.grad += w.grad (∑△w)
            optimizer.step()           # w = w - lr * w.grad   

    # Evaluate on validation set
    model.eval()

    with torch.no_grad():     # In this with block, requires_grad=False
        y_val_pred_proba = model(X_val_tensor)
        y_val_pred_label = (y_val_pred_proba >= 0.5).float()    # Apply threshold and to float as y_val_tensor is float.
        accuracy = (y_val_pred_label == y_val_tensor).float().mean().item()
    print(f'Accuracy on valication set: {accuracy * 100:.2f}')

    return model

In [190]:
def predict_lstm(df, model):
    # Get X and preprocess in the same way as the train set
    X = df.drop(columns=['icustay_id', 'hospital_expire_flag'])
    X = np.reshape(X, (X.shape[0], 1, X.shape[1]))
    X_tensor = torch.tensor(X, dtype=torch.float32, device=device)

    model.eval()
    with torch.no_grad():
        y_pred_proba = model(X_tensor)
        y_pred_label = (y_pred_proba >= 0.5).int().numpy()

    return y_pred_label

### 3) Training and Validation

In [191]:
# Train one LSTM model on each feature dataframe
models = {}

for col in timeseries_features:
    df_tmp = df_timeseries[col]
    df_train = df_tmp[df_tmp['icustay_id'].isin(id_train)]    # No need to sort here
    df_val = df_tmp[df_tmp['icustay_id'].isin(id_val)]

    print(f'Training LSTM with the feature: [{col}] =======================')
    models[col] = train_lstm(df_train, df_val)

Training LSTM with the feature: [heartrate] =======================
Accuracy on valication set: 68.00
Training LSTM with the feature: [sysbp] =======================
Accuracy on valication set: 68.00
Training LSTM with the feature: [diabp] =======================
Accuracy on valication set: 68.00
Training LSTM with the feature: [meanbp] =======================
Accuracy on valication set: 72.00
Training LSTM with the feature: [resprate] =======================
Accuracy on valication set: 68.00
Training LSTM with the feature: [spo2] =======================
Accuracy on valication set: 68.00

As the training set is not big enough to train neural network, the validation accuracy is not high.

### 4) Prediction with the Trained LSTM

* Prediction on Train, Validation Sets

Here, we will make a prediction and put it side by side with the actual label dataframe. To align actual and prediction values of the same `icustay_id`  , **sorting** by `icustay_id` is important.

In [192]:
# Split actual df_label (y) into train, validation
df_label_train = df_label[df_label['icustay_id'].isin(id_train)].sort_values(by='icustay_id')
df_label_val = df_label[df_label['icustay_id'].isin(id_val)].sort_values(by='icustay_id')

# Prediction
for col in timeseries_features:
    print(f'[{col}] =============================================')
    df_tmp = df_timeseries[col]

    df_train = df_tmp[df_tmp['icustay_id'].isin(id_train)].sort_values(by='icustay_id')
    y_pred_train = predict_lstm(df_train, models[col])
    df_label_train[f'{col}_pred'] = y_pred_train    # Add y_pred to y_true
    acc_train = (df_label_train['hospital_expire_flag'] == y_pred_train).mean()

    print('Accuracy on train set:', round(acc_train, 2))

    df_val = df_tmp[df_tmp['icustay_id'].isin(id_val)].sort_values(by='icustay_id')
    y_pred_val = predict_lstm(df_val, models[col])
    df_label_val[f'{col}_pred'] = y_pred_val
    acc_val = (df_label_val['hospital_expire_flag'] == y_pred_val).mean()

    print('Accuracy on validation set:', round(acc_val, 2))

[heartrate] =============================================
Accuracy on train set: 0.74
Accuracy on validation set: 0.68
[sysbp] =============================================
Accuracy on train set: 0.71
Accuracy on validation set: 0.68
[diabp] =============================================
Accuracy on train set: 0.75
Accuracy on validation set: 0.68
[meanbp] =============================================
Accuracy on train set: 0.77
Accuracy on validation set: 0.72
[resprate] =============================================
Accuracy on train set: 0.7
Accuracy on validation set: 0.68
[spo2] =============================================
Accuracy on train set: 0.74
Accuracy on validation set: 0.68

* Prediction on Test Set

In [193]:
# Actual test label (y)
df_label_test = df_label[df_label['icustay_id'].isin(id_test)].sort_values(by='icustay_id')

for col in timeseries_features:
    print(f'[{col}] =============================================')
    df_tmp = df_timeseries[col]

    df_test = df_tmp[df_tmp['icustay_id'].isin(id_test)].sort_values(by='icustay_id')
    y_pred_test = predict_lstm(df_test, models[col])
    df_label_test[f'{col}_pred'] = y_pred_test
    acc_test = (df_label_test['hospital_expire_flag']==y_pred_test).mean()

    print('Accuracy on test set:', acc_test)

[heartrate] =============================================
Accuracy on test set: 0.6
[sysbp] =============================================
Accuracy on test set: 0.6
[diabp] =============================================
Accuracy on test set: 0.56
[meanbp] =============================================
Accuracy on test set: 0.6
[resprate] =============================================
Accuracy on test set: 0.6
[spo2] =============================================
Accuracy on test set: 0.6

The generalised performace on test set is quite similar with the one on validation set.